# Generated by Django 5.1.4 on 2024-12-24 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(default='', max_length=20)),
                ('model', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(default='', max_length=50)),
                ('phoneNumber', models.CharField(default='', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('skills', models.CharField(default='', max_length=255)),
                ('login', models.CharField(default='', max_length=20)),
                ('password', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Dan', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default='', max_length=10)),
                ('description', models.CharField(default='', max_length=255)),
                ('status', models.CharField(default='', max_length=20)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.car')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.client')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.master')),
            ],
        ),
    ]
